FROM ubuntu:24.04
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
ENV GOROOT=/opt/golang/go/
ENV DEBIAN_FRONTEND=noninteractive
RUN apt -y update
ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh
RUN source /tmp/install_deps.sh && install_deps_ubuntu24.04
ADD . /opt/asconfig
WORKDIR /opt/asconfig
ENTRYPOINT ["/opt/asconfig/.github/docker/entrypoint.sh"]
CMD ["-b"]
