FROM redhat/ubi8
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
RUN useradd -u 9001 -m build

ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh

RUN source /tmp/install_deps.sh && install_deps_redhat-el8
ADD --chown=build:build . /opt/asconfig
USER build

WORKDIR /opt/asconfig
ENTRYPOINT ["/opt/asconfig/.github/docker/entrypoint.sh"]
CMD ["-b"]
