FROM redhat/ubi9:9.6
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
ENV GOROOT=/opt/golang/go/
ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh
RUN source /tmp/install_deps.sh && install_deps_redhat-el9
ADD . /opt/asconfig
WORKDIR /opt/asconfig
ENTRYPOINT ["/opt/asconfig/.github/docker/entrypoint.sh"]
CMD ["-b"]
