FROM amazonlinux:2023
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
ENV GOROOT=/opt/golang/go
RUN dnf install -y shadow-utils && useradd -u 9001 -m build

ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh

RUN source /tmp/install_deps.sh && install_deps_amazon-2023
ADD --chown=build:build . /opt/asconfig
USER build

WORKDIR /opt/asconfig
ENTRYPOINT ["/opt/asconfig/.github/docker/entrypoint.sh"]
CMD ["-b"]
