FROM ubuntu:22.04
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

ARG DEBUG=0
ENV DEBUG=${DEBUG}

RUN apt -y update
ADD .github/scripts/entrypoint.sh /tmp/entrypoint.sh

RUN /tmp/entrypoint.sh -i

RUN if [[ $DEBUG -ne 0 ]]; then apt -y clean && rm -rf /var/lib/apt/lists/*; fi

ADD . /opt/asconfig
WORKDIR /opt/asconfig

ENTRYPOINT ["/opt/asconfig/.github/scripts/entrypoint.sh"]
CMD ["-b"]
