package cmd

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/aerospike/aerospike-management-lib/asconfig"
	"github.com/aerospike/asconfig/conf"
	"github.com/aerospike/asconfig/conf/metadata"
	"github.com/spf13/cobra"
)

const (
	convertArgMax         = 1
	defaultOutputFileName = "config"
)

var (
	errTooManyArguments            = fmt.Errorf("expected a maximum of %d arguments", convertArgMax)
	errFileNotExist                = fmt.Errorf("file does not exist")
	errMissingAerospikeVersion     = fmt.Errorf("missing required flag '--aerospike-version'")
	errInvalidAerospikeVersion     = fmt.Errorf("aerospike version must be in the form <a>.<b>.<c>")
	errUnsupportedAerospikeVersion = fmt.Errorf("aerospike version unsupported")
	errInvalidFormat               = fmt.Errorf("invalid format flag")
	errMissingFormat               = fmt.Errorf("missing format flag")
)

func init() {
	rootCmd.AddCommand(convertCmd)
}

var convertCmd = newConvertCmd()

func newConvertCmd() *cobra.Command {
	var cfgData []byte
	res := &cobra.Command{
		Use:   "convert [flags] <path/to/config_file>",
		Short: "Convert between yaml and Aerospike config format.",
		Long: `Convert is used to convert between yaml and aerospike configuration
				files. Input files are converted to their opposite format, yaml -> conf, conf -> yaml.
				The convert command validates the configuration file for compatibility with the Aerospike
				version passed to the --aerospike-version option, unless
				version metadata is present in the file or the --force option is used.
				Aerospike Database metadata is written to files generated by asconfig.
				Usage examples...
				convert local file "aerospike.yaml" to aerospike config format for version 6.2.0 and
				write it to local file "aerospike.conf."
				Ex: asconfig convert --aerospike-version "6.2.0" aerospike.yaml --output aerospike.conf
				Short form flags and source file only conversions are also supported.
				In this case, -a is the server version and using only a source file means
				the result will be written to stdout.
				Ex: asconfig convert -a "6.2.0" aerospike.yaml
				Normally the file format is inferred from file extensions ".yaml" ".conf" etc.
				Source format can be forced with the --format flag.
				Ex: asconfig convert -a "6.2.0" --format yaml example_file
				If a file path is not provided, asconfig reads the file contents from stdin.
				Ex: asconfig convert -a "6.4.0"
				If the file has been converted by asconfig before, the --aerospike-version option is not needed.
				Ex: asconfig convert -a "6.4.0" aerospike.yaml | asconfig convert --format conf`,
		RunE: func(cmd *cobra.Command, args []string) error {
			logger.Debug("Running convert command")

			// read stdin by default
			var srcPath string
			if len(args) == 0 {
				srcPath = os.Stdin.Name()
			} else {
				srcPath = args[0]
			}

			asVersion, err := cmd.Flags().GetString("aerospike-version")
			if err != nil {
				return err
			}

			logger.Debugf("Processing flag aerospike-version value=%s", asVersion)

			force, err := cmd.Flags().GetBool("force")
			if err != nil {
				return err
			}

			logger.Debugf("Processing flag force value=%t", force)

			srcFormat, err := getConfFileFormat(srcPath, cmd)
			if err != nil {
				return err
			}

			logger.Debugf("Processing flag format value=%v", srcFormat)

			var outFmt conf.Format
			switch srcFormat {
			case conf.AsConfig:
				outFmt = conf.YAML
			case conf.YAML:
				outFmt = conf.AsConfig
			default:
				return fmt.Errorf("%w: %s", errInvalidFormat, srcFormat)
			}

			// if the version option is empty,
			// try populating from the metadata
			if asVersion == "" {
				asVersion, err = getMetaDataItem(cfgData, metaKeyAerospikeVersion)
				if err != nil && !force {
					return errors.Join(errMissingAerospikeVersion, err)
				}
			}

			// load
			asconfig, err := conf.NewASConfigFromBytes(mgmtLibLogger, cfgData, srcFormat)

			if err != nil {
				return err
			}

			// validate
			if !force {
				verrs, err := conf.NewConfigValidator(asconfig, mgmtLibLogger, asVersion).Validate()
				if err != nil || verrs != nil {
					return errors.Join(err, verrs)
				}
			}

			// convert
			out, err := conf.NewConfigMarshaller(asconfig, outFmt).MarshalText()
			if err != nil {
				return err
			}

			// prepend metadata to the config output
			mtext, err := genMetaDataText(
				cfgData,
				nil,
				map[string]string{
					metaKeyAerospikeVersion: asVersion,
					metaKeyAsconfigVersion:  VERSION,
				},
			)
			if err != nil {
				return err
			}
			out = append(mtext, out...)

			outputPath, err := cmd.Flags().GetString("output")
			if err != nil {
				return err
			}

			if stat, err := os.Stat(outputPath); !errors.Is(err, os.ErrNotExist) && stat.IsDir() {
				// output path is a directory so write a new file to it
				outFileName := filepath.Base(srcPath)
				if srcPath == os.Stdin.Name() {
					outFileName = defaultOutputFileName
				}

				outFileName = strings.TrimSuffix(outFileName, filepath.Ext(outFileName))

				outputPath = filepath.Join(outputPath, outFileName)
				if outFmt == conf.YAML {
					outputPath += ".yaml"
				} else if outFmt == conf.AsConfig {
					outputPath += ".conf"
				} else {
					return fmt.Errorf("output format unrecognized %w", errInvalidFormat)
				}
			}

			var outFile *os.File
			if outputPath == os.Stdout.Name() {
				outFile = os.Stdout
			} else {
				outFile, err = os.OpenFile(outputPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
				if err != nil {
					return err
				}

				defer outFile.Close()
			}

			logger.Debugf("Writing converted data to: %s", outputPath)
			_, err = outFile.Write([]byte(out))
			return err

		},
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > convertArgMax {
				return errTooManyArguments
			}

			if len(args) > 0 {
				source := args[0]
				if _, err := os.Stat(source); errors.Is(err, os.ErrNotExist) {
					return errors.Join(errFileNotExist, err)
				}
			}

			// validate flags
			_, err := cmd.Flags().GetString("output")
			if err != nil {
				return err
			}

			force, err := cmd.Flags().GetBool("force")
			if err != nil {
				return err
			}

			// read stdin by default
			var srcPath string
			if len(args) == 0 {
				srcPath = os.Stdin.Name()
			} else {
				srcPath = args[0]
			}

			cfgData, err = os.ReadFile(srcPath)
			if err != nil {
				return err
			}

			metaData := map[string]string{}
			metadata.Unmarshal(cfgData, metaData)

			// if the aerospike server version is in the cfg file's
			// metadata, don't mark --aerospike-version as required
			var aeroVersionRequired bool
			if _, ok := metaData[metaKeyAerospikeVersion]; !ok {
				if !force {
					cmd.MarkFlagRequired("aerospike-version")
					aeroVersionRequired = true
				}
			}

			av, err := cmd.Flags().GetString("aerospike-version")
			if err != nil {
				return err
			}

			if aeroVersionRequired {
				if av == "" {
					return errors.Join(errMissingAerospikeVersion, err)
				}

				supported, err := asconfig.IsSupportedVersion(av)
				if err != nil {
					return errors.Join(errInvalidAerospikeVersion, err)
				}

				// TODO include valid versions in the error message
				// asconfig lib needs a getSupportedVersions func
				if !supported {
					return errUnsupportedAerospikeVersion
				}
			}

			formatString, err := cmd.Flags().GetString("format")
			if err != nil {
				return errors.Join(errMissingFormat, err)
			}

			_, err = ParseFmtString(formatString)
			if err != nil && formatString != "" {
				return errors.Join(errInvalidFormat, err)
			}

			return nil
		},
	}

	// flags and configuration settings
	// aerospike-version is marked required in this cmd's PreRun if the --force flag is not provided
	asCommonFlags := getCommonFlags()
	res.Flags().AddFlagSet(asCommonFlags)
	res.Flags().BoolP("force", "f", false, "Override checks for supported server version and config validation")
	res.Flags().StringP("output", "o", os.Stdout.Name(), "File path to write output to")
	res.Flags().StringP("format", "F", "conf", "The format of the source file(s). Valid options are: yaml, yml, and conf.")

	res.Version = VERSION

	return res
}
